### ISSUE TITLE
Fails to get started

### ISSUE THREAD

**Issue by Liturgist** [mishra-ankit/jsoneditor-standalone#8]
I tried to follow the directions. What am I missing? Where can I find documentation about using a schema?

```
C:>ver
Microsoft Windows [Version 10.0.18363.900]

C:>npm --version
3.10.10

C:>npm i -g jsoneditor-standalone
C:\Users\lit\AppData\Roaming\npm\jsoneditor -> C:\Users\lit\AppData\Roaming\npm\node_modules\jsoneditor-standalone\bin\script.js
C:\Users\lit\AppData\Roaming\npm
`-- jsoneditor-standalone@1.0.3

C:>C:\Users\lit\AppData\Roaming\npm\jsoneditor.cmd
C:\Users\lit\AppData\Roaming\npm\node_modules\jsoneditor-standalone\bin\script.js:10
(async () => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by mishra-ankit** [comment]
@Liturgist Thanks for taking the time to open the issue.
I'm guessing it could be due to an older version of Node. (i.e. < 7.6) refer [here](https://stackoverflow.com/a/37815872/1150183). If that's the case strongly suggest upgrading Node version. 
If not please let me know, and I can look into it further, as it seems to work for me on Node v12.x.x. 

That being said, maybe I should update instructions with minimum node version required.

**Comment by Liturgist** [comment]
I admit to not being experienced with node and npm. I installed a more recent version, but not able to install.

```
Microsoft Windows [Version 10.0.17763.1217]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Program Files\nodejs>node --version
v12.18.2

C:\Program Files\nodejs>npm --version
6.14.5

C:\Program Files\nodejs>npm i -g jsoneditor-standalone
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/jsoneditor-standalone failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lit\AppData\Roaming\npm-cache\_logs\2020-07-14T16_46_26_318Z-debug.log

C:\Program Files\nodejs>type C:\Users\lit\AppData\Roaming\npm-cache\_logs\2020-07-14T16_46_26_318Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'jsoneditor-standalone'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose npm-session 515069f975a426f2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for jsoneditor-standalone@latest request to https://registry.npmjs.org/jsoneditor-standalone failed, reason: unable to get local issuer certificate
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 247ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/jsoneditor-standalone failed, reason: unable to get local issuer certificate
11 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:315:20)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:426:9)
11 verbose stack     at TLSSocket.emit (events.js:315:20)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)
11 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
12 verbose cwd C:\Program Files\nodejs
13 verbose Windows_NT 10.0.17763
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "jsoneditor-standalone"
15 verbose node v12.18.2
16 verbose npm  v6.14.5
17 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
18 error errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
19 error request to https://registry.npmjs.org/jsoneditor-standalone failed, reason: unable to get local issuer certificate
20 verbose exit [ 1, true ]
```

**Comment by mishra-ankit** [comment]
Ah, I see. Does it let you install any other npm pakcages (e.g. react, nodemon) ?
I'd guess you're behind a proxy perhaps. I found something similar here https://stackoverflow.com/a/46408398. Hope that helps.

**Comment by Liturgist** [comment]
I agree this may be a corporate firewall/VPN issue.
