### ISSUE TITLE
Local machine fails to start

### ISSUE THREAD

**Issue by Liturgist** [mishra-ankit/jsoneditor-standalone#9]
On a personal/home Microsoft Windows [Version 10.0.18363.900] machine, I have the following problem. Any suggestions?
```
C:>npm i -g jsoneditor-standalone
C:\Users\pwatson\AppData\Roaming\npm\jsoneditor -> C:\Users\lit\AppData\Roaming\npm\node_modules\jsoneditor-standalone\bin\script.js
+ jsoneditor-standalone@1.0.4
updated 1 package in 10.712s

20:44:34.19  C:\Program Files\nodejs
C:>jsoneditor
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'opn'
Require stack:
- C:\Users\lit\AppData\Roaming\npm\node_modules\jsoneditor-standalone\bin\script.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\lit\AppData\Roaming\npm\node_modules\jsoneditor-standalone\bin\script.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lit\\AppData\\Roaming\\npm\\node_modules\\jsoneditor-standalone\\bin\\script.js'
  ]
}
```

**Comment by mishra-ankit** [comment]
Uhoh, looks like there's a dependency missing from package.json.
I'll release a new version with fix ASAP. Until then you can workaround by installing it manually (npm i opn)

**Comment by mishra-ankit** [comment]
Thanks for bringing this up. 
Should be fixed now (v1.0.5). I can close this once it works for you.

**Comment by Liturgist** [comment]
1.0.5 installed and appears to be working. Thanks.

I still need to know how to use a JSON schema file with jsoneditor.

**Comment by mishra-ankit** [comment]
I think, that feature isn't exposed as of now. I'll add it to the feature list for next release. 

PR are very much welcome if you have solved it locally already.
